[package]
name = "bevy_behave"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
dyn-clone = "1.0.18"
ego-tree = "0.10.0"

[dev-dependencies]
bevy_screen_diagnostics = {git = "https://github.com/mlupo19/bevy_screen_diagnostics.git", branch = "personal/0.15"}
bevy_pancam = "0.17"
rand = "*"

[lints.clippy]
type_complexity = "allow"
